import {
  MatButtonModule,
  MatCheckboxModule,
  MatSnackBarModule,
  MatListModule,
  MatSidenavModule,
  MatFormFieldModule,
  MatInputModule,
  MatRadioModule,
  MatSelectModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatIconModule,
  MatToolbarModule,
  MatCardModule,
  MatTabsModule,
  MatProgressBarModule,
  MatChipsModule,
  MatButtonToggleModule,
  MatProgressSpinnerModule,
  MatStepperModule,
  MatTableModule,
} from '@angular/material';

import { NgModule, ApplicationRef } from '@angular/core';

@NgModule({
  imports: [
    MatButtonModule,
    MatCheckboxModule,
    MatSnackBarModule,
    MatListModule,
  MatSidenavModule,
  MatFormFieldModule,
  MatInputModule,
  MatRadioModule,
  MatSelectModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatIconModule,
  MatToolbarModule,
  MatCardModule,
  MatTabsModule,
  MatProgressBarModule,
  MatChipsModule,
  MatButtonToggleModule,
  MatProgressSpinnerModule,
  MatStepperModule,
  MatTableModule,
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatSnackBarModule,
    MatListModule,
  MatSidenavModule,
  MatFormFieldModule,
  MatInputModule,
  MatRadioModule,
  MatSelectModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatIconModule,
  MatToolbarModule,
  MatCardModule,
  MatTabsModule,
  MatProgressBarModule,
  MatChipsModule,
  MatButtonToggleModule,
  MatProgressSpinnerModule,
  MatStepperModule,
  MatTableModule
  ]
})
export class RacetrackMaterialModule {

}
